server:
  port: 8906

spring:
  datasource:
    url: jdbc:postgresql://pgsql/universe?currentSchema=leob
    username: postgres
    password: 123456

api:
  fcm:
    keyPath: /proj/config/leob-key.json
    dbUrl: https://leob-bd12a.firebaseio.com
