server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1/universe?currentSchema=leob
    username: postgres
    password: 123456
api:
  fcm:
    keyPath: /Users/chengweiou/Documents/project/universe/leob/src/main/resources/fcm/leob-key.json
    dbUrl: https://leob-bd12a.firebaseio.com
